spring:
  application:
    name: reservation-service
  data:
    rest:
      base-path: /v1/reservations
  config:
     import: optional:configserver:http://localhost:8099 
  datasource:
    url: jdbc:mysql://localhost:3306/reservationdb?useSSL=false&serverTimezone=UTC
    username: root
    password: Epam1234$
  jpa:
    show-sql: false 
    hibernate:
      naming: 
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  cloud:
    stream: 
      bindings:
        reservationCreateRequest-out: 
          destination: crs-reservation-event-topic
          content-type: application/json  
        createPaymentRequest-in-0: 
          destination: crs-payment-cmd-topic
          content-type: application/json
        paymentCreatedEvent-out: 
          destination: crs-payment-event-topic
          content-type: application/json
      kafka: 
        binder:
          brokers: "localhost:9092"
    function: 
      definition: createPaymentRequest
      
         
            
  
spring.cloud.config.name: config
#spring.cloud.config.discovery.enabled: true
#spring.cloud.config.discovery.serviceId: CRS-CONFIG-SERVER
management.endpoints.web.exposure.include: refresh   
feign:
  circuitbreaker:
    enabled: true
              
server:
  port: 8092
  servlet:
    context-path: /api  
      
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/ 
spring.sleuth.sampler.probability: 1.0   
message:
  errorConfig:
      genericErrorCode: RC_GENERIC_ERROR
      genericErrorMessage: There was an error while processing your request. Please try again.
      inputValidationErrorCode: RC_INPUT_VALIDATION_ERROR
      guestNotFoundErrorCode: RC_GUEST_NOT_FOUND
      guestNotFoundErrorMessasge: Guest Id %s not found.
      hotelRoomNotFoundErrorCode: RC_HOTEL_ROOM_NOT_FOUND
      hotelRoomNotFoundErrorMessasge: Hotel Id %s with room Id %s not found.
      reservationNotFoundErrorCode: RC_RESERVATION_NOT_FOUND_ERROR
      reservationFoundErrorMessage: Reservation Id %s not found.
      cardStoreNotFoundErrorCode: RC_CARD_STORE_NOT_FOUND_ERROR
      cardStoreFoundErrorMessage: CardStore Id %s not found.
  messageConfig:
      reservationSuccessMessage: "Successfully room allocated. Reservation Id: %s"
       
    
guest.service.name: GUEST-SERVICE
hotel.service.name: HOTEL-SERVICE
gateway.service.name: CRS-GATEWAY


resilience4j.circuitbreaker:
  instances:
    hrsClient:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        - java.util.concurrent.TimeoutException
        - org.springframework.web.client.ResourceAccessException
        - org.springframework.web.client.HttpClientErrorException
      ignoreExceptions:


 # Axon
#axon.serializer.general: jackson   

axon:
    eventhandling:
        processors:
            name:
                mode: tracking
                source: eventBus
                
                
                
spring.main.allow-bean-definition-overriding: true 
security.secret: secretsecretsecretsecretsecretsecretsecretsecret  
#in second   
security.expiration:  3600     
security.appId: crs
security.pass: crs             